### ISSUE TITLE
Google login issue happening

### ISSUE THREAD

**Issue by Subhojit1992** [heresy/angular2-social-login-example#14] opened 2017-08-24 06:04 UTC
I using angular 4+ 
got this issue when page load

details:"Failed to read the 'localStorage' property from 'Window': Access is denied for this document."
error:"idpiframe_initialization_failed"

and when hit the login button 
console log this error
error: "popup_closed_by_user"

**Comment by kpsrinivas** [comment] 2017-08-24 06:07
This could be the cause - https://stackoverflow.com/questions/30481516/iframe-in-chrome-error-failted-to-read-localstorage-from-window-access-den 

This is not an issue of this plugin. Closing it.

**Closed as completed by kpsrinivas** 2017-08-24 06:07 UTC

**Comment by Subhojit1992** [comment] 2017-08-24 06:14
So, can you let me know I I fix this?
